# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b44384574c84e68c2951cc0c11159454f9c9a3fd6b53efac603c09f3189a5286ea439f8bddce23a048e1c72e1b40fff5ef623c669f61bb69ff7cdc7b5636fbd2

test:
  secret_key_base: ffc2cb72f25562c0b24cb1fb0e0a778619c3585fe07dc6723ce0594d59578a14a886d92295f531b9611790090feef602180e565e9c86cadea9e589aff5a6b65e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
